In [2]:
pip install numpy pandas matplotlib seaborn


Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'3.0.5'

In [5]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)

In [6]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   model_year           10000 non-null  int64  
 1   origin               10000 non-null  str    
 2   fuel_type            10000 non-null  str    
 3   drivetrain           10000 non-null  str    
 4   num_doors            10000 non-null  int64  
 5   engine_displacement  10000 non-null  int64  
 6   num_cylinders        10000 non-null  int64  
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64  
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB


In [8]:
##  Q2 - Records count

In [9]:
df.shape

(10000, 11)

In [10]:
df.shape[0]

10000

In [11]:
## Q3 - Number of fuel types:

In [12]:
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [13]:
df["fuel_type"].nunique()

3

In [14]:
## Column with missing value 

In [15]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [16]:
df.isnull().any().sum()

np.int64(2)

In [17]:
## Max Fuel efficiency 

In [18]:
asia_cars = df[df["origin"] == "Asia"]
asia_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4


In [19]:
asia_cars["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [20]:
## Step 1 Median Horsepower

In [21]:
original_median = df["horsepower"].median()
original_median

np.float64(254.0)

In [22]:
## Step 2 Most Frequent value 

In [23]:
horsepower_mode = df["horsepower"].mode()[0]
horsepower_mode

np.float64(252.0)

In [24]:
## Step 3 fill the missing vales

In [25]:
df_filled = df.copy()

In [26]:
df_filled["horsepower"] = df_filled["horsepower"].fillna(horsepower_mode) 

In [27]:
df_filled["horsepower"].isnull().sum()

np.int64(0)

In [28]:
## calculate the median again

In [29]:
new_median = df_filled["horsepower"].median()
print("orinal median:", original_median)
print ("Most frequent value:", horsepower_mode)
print ("Median after filling:",  new_median)

orinal median: 254.0
Most frequent value: 252.0
Median after filling: 252.0


In [30]:
## Q7 Sum of Weights

In [31]:
## Select an asian car

In [32]:
asia_cars = df[df["origin"] == "Aisa"]

In [33]:
## Select two columns

In [34]:
selected_columns = asia_cars[["vehicle_weight", "model_year"]]

In [35]:
## Step3: Select the first seven rows

In [45]:
asia_cars = df[df["origin"] == "Asia"]
selected_columns = asia_cars[["vehicle_weight", "model_year"]]
first_seven = selected_columns.head(7)

print("Asian cars:", len(asia_cars))
display(first_seven)

Asian cars: 2994


,vehicle_weight,model_year
2,4240,1996
6,4310,1992
8,4230,1997
10,4420,1978
15,3950,2007
16,4750,2021
22,4450,2019


In [37]:
## convert to numpy array 

In [47]:
X = first_seven.to_numpy()
X
print(X.shape)

(7, 2)


In [39]:
X.shape

(0, 2)

In [40]:
## Multiple the transpose by X

In [48]:
XTX = X.T @ X
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]


In [49]:
## Step 6: Invert XTX

In [51]:
XTX_inverse = np.linalg.inv(XTX)

print(XTX_inverse)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]


In [52]:
## Create an array y

In [53]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [54]:
## Step 8: Calculate w

In [55]:
w = XTX_inverse @ X.T @ y

w


array([0.13644777, 0.2327492 ])

In [56]:
##  Step 9: Calculate the sum

In [58]:
w.sum()

np.float64(0.36919696904925203)

In [59]:
round(w.sum(), 3)

np.float64(0.369)